---
  default_language_version:
    python: python3.8
  repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
        - id: check-executables-have-shebangs
        - id: check-merge-conflict
        - id: detect-private-key
        - id: end-of-file-fixer
        - id: sort-simple-yaml
        - id: trailing-whitespace
        - id: check-added-large-files
    - repo: https://github.com/thoughtworks/talisman
      rev: v1.27.0
      hooks:
        - id: talisman-commit
          entry: cmd --githook pre-commit
